services:
  postgres:
    image: postgres:18.0-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${STORE_PG_DB}
      POSTGRES_USER: ${STORE_PG_USER}
      POSTGRES_PASSWORD: ${STORE_PG_PASSWORD}
    expose:
      - "${STORE_PG_PORT}"
    volumes:
      - ./dumps/pg_dumps:/docker-entrypoint-initdb.d
      - ./volumes/pgdata:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${STORE_PG_USER} -d ${STORE_PG_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${STORE_MARIADB_DB} # optional: init DB
      MARIADB_USER: ${STORE_MARIADB_USER} # optional: app user
      MARIADB_ROOT_PASSWORD: ${STORE_MARIADB_DB} # change this
      TZ: Europe/Amsterdam # optional
    expose:
      - "${STORE_MARIADB_PORT}"
    volumes:
      - ./volumes/mariadb:/var/lib/mysql

  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - "${MONGO_PORT}"
    volumes:
      - ./volumes/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongod", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8.2.2-alpine3.22
    restart: unless-stopped
    environment:
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_DB_USER}
      REDIS_PASS: ${REDIS_DB_PASSWORD}
    expose:
      - "${REDIS_DB_PORT}"
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  tarantool:
    image: tarantool/tarantool:3.5.0
    restart: unless-stopped
    expose:
      - "${TARANTOOL_DB_PORT}"
    volumes:
      - ./volumes/tarantool:/var/lib/tarantool
      - ./dumps/tarantool/script:/usr/local/share/tarantool
    command: tarantool /usr/local/share/tarantool/app.init.lua
